version: "3.5"
services:
  postgres:
    container_name: postgres
    build:
      context: .docker/postgres
      dockerfile: Dockerfile
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
      - .docker/postgres/scripts:/etc/postgresql/scripts
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: on-failure
    tty: true
